# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0
"""Tool enabling agents to consult the long-lived Project Expert Agent."""

from google.adk.tools import ToolContext

from providers.adk.agents.project_expert import get_project_expert_agent
from providers.adk.utilities.async_runner import run_agent_node
from utilities.decorators import limit_tool_output
from utilities.logger import logger


@limit_tool_output
async def ask_project_expert(
    question: str,
    tool_context: ToolContext | None = None,
) -> str:
    """Consults the Project Expert Agent for project-level architectural guidance, design rationale,

    subsystem boundaries, or hardware/firmware interface conventions. Use this tool when you need
    clarification on whether a behavior is intentional, how components interact, or what the threat
    model dictates for a specific component.

    Args:
        question: The specific technical or architectural question about the project.

    Returns:
        The Project Expert's answer grounded in the project codebase and threat model.
    """
    if not tool_context or not tool_context.state:
        return "Error: ToolContext not available to access Project Expert."

    state = tool_context.state
    model = state.get("model")
    threat_model = state.get("threat_model_context", "")
    summary = state.get("project_expert_summary", "")

    if not model:
        if summary:
            return f"Project Expert Agent not actively loaded. Here is the initial exploration summary:\n\n{summary}"
        return "Project Expert Agent is not available in the current session."

    logger.debug(f"[Tool Execution] ask_project_expert: {question[:100]}...")

    project_expert_agent = get_project_expert_agent(model, threat_model)

    # Build targeted prompt for the Project Expert Agent
    context_prefix = ""
    if summary:
        context_prefix = f"Background Architecture Summary:\n{summary}\n\n"

    query_input = (
        f"{context_prefix}"
        f"A downstream security agent has consulted you with the following question regarding the project:\n\n"
        f"Question: {question}\n\n"
        "Please provide a precise, grounded answer referencing project files, conventions, or threat model constraints where applicable."
    )

    try:
        res = await run_agent_node(
            tool_context,
            project_expert_agent,
            node_input=query_input,
            run_id=f"expert_query_{abs(hash(question)) % 100000}",
        )

        output_text = (
            getattr(res, "output", None)
            or getattr(res, "text", None)
            or (str(res) if res is not None else "No response generated by Project Expert.")
        )
        return str(output_text).strip()
    except Exception as e:
        logger.warning(f"Error querying Project Expert Agent: {e}")
        if summary:
            return (
                f"Error querying Project Expert Agent ({e}). "
                f"Falling back to initial exploration summary:\n\n{summary}"
            )
        return f"Error querying Project Expert Agent: {e}"
